/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellondk_AppData */

#ifndef _Included_com_example_hellondk_AppData
#define _Included_com_example_hellondk_AppData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellondk_AppData
 * Method:    putData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hellondk_AppData_putData
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_hellondk_AppData
 * Method:    saveDataInfoFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellondk_AppData_saveDataInfoFile
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellondk_AppData
 * Method:    getValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellondk_AppData_getValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_hellondk_AppData
 * Method:    loadData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellondk_AppData_loadData
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellondk_AppData
 * Method:    nativeSetAssetManager
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hellondk_AppData_nativeSetAssetManager
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
